version: "3.2"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=8H4a10032024
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - shared-network  # Adiciona a rede compartilhada

volumes:
  n8n_data:

networks:
  n8n-net:
    name: n8n-net
    driver: bridge
  shared-network:    # Define a rede compartilhada
    driver: bridge
    external: true
