version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8090:8080"  # Porta 8090 no host mapeada para a porta 8080 do contêiner
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net  # Adicione a rede aqui

volumes:
  evolution_instances:

networks:
  evolution-net:
    external: true  # Define que a rede já foi criada
